<?php require_once __DIR__ . '/../../app/config/admin-helpers.php';
$pageTitle = 'Produtos';
require __DIR__ . '/../../app/views/includes/header.php';
$rows = adminProducts();
$cats = adminCategories();
$suppliers = suppliers(); ?><link rel="stylesheet" href="/assets/css/admin.css">
<section class="page-intro compact"><p class="eyebrow">Operação / catálogo</p><h1>Produtos.</h1><p>Crie peças vinculadas a uma categoria, fornecedor e quantidade de estoque.</p></section>
<div class="admin-layout"><form class="settings-form admin-form" action="/actions.php" method="post"><input type="hidden" name="action" value="create_product"><p class="eyebrow">Nova peça</p><label>Nome do produto<input required type="text" name="name" placeholder="Ex.: Jaqueta Heritage"></label><label>Descrição<textarea name="description" rows="4" placeholder="Detalhes da peça"></textarea></label><label>Preço<input required type="number" step="0.01" name="price" placeholder="0,00"></label><label>Categoria<select name="category_id"><?php foreach ($cats as $cat) :
    ?><option value="<?= $cat['id'] ?>"><?= htmlspecialchars($cat['name']) ?></option><?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          endforeach; ?></select></label><label>Fornecedor<select name="supplier_id"><option value="">Sem fornecedor</option><?php foreach ($suppliers as $supplier) :
    ?><option value="<?= $supplier['id'] ?>"><?= htmlspecialchars($supplier['name']) ?></option><?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          endforeach; ?></select></label><label>Quantidade inicial<input type="number" name="quantity" min="0" value="0"></label><button class="button dark" type="submit">Criar produto ↗</button></form><div class="admin-table"><div class="table-head"><span>Produto</span><span>Categoria</span><span>Fornecedor</span><span>Estoque</span></div><?php foreach ($rows as $row) :
    ?><div class="table-row"><strong><?= htmlspecialchars($row['name']) ?></strong><span><?= htmlspecialchars($row['category'] ?? '—') ?></span><span><?= htmlspecialchars($row['supplier'] ?? '—') ?></span><span><?= (int)($row['quantity'] ?? 0) ?></span></div><?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          endforeach; ?></div></div>
<?php require __DIR__ . '/../../app/views/includes/footer.php'; ?>
