<?php require_once __DIR__ . '/../../app/config/admin-helpers.php';
$pageTitle = 'Fornecedores';
require __DIR__ . '/../../app/views/includes/header.php';
$rows = suppliers(); ?><link rel="stylesheet" href="/assets/css/admin.css">
<section class="page-intro compact"><p class="eyebrow">Operação / parceiros</p><h1>Fornecedores.</h1><p>Cadastre quem abastece o catálogo e acompanhe sua relação com produtos.</p></section>
<div class="admin-layout"><form class="settings-form admin-form" action="/actions.php" method="post"><input type="hidden" name="action" value="create_supplier"><p class="eyebrow">Novo fornecedor</p><label>Nome da empresa<input required type="text" name="name" placeholder="Ex.: Atelier Norte"></label><label>E-mail de contato<input type="email" name="email" placeholder="contato@empresa.com"></label><label>Telefone<input type="text" name="phone" placeholder="+55 11 ..."></label><button class="button dark" type="submit">Cadastrar fornecedor ↗</button></form><div class="admin-table"><div class="table-head"><span>Fornecedor</span><span>Contato</span><span>Produtos</span><span>Status</span></div><?php if (!$rows) :
    ?><div class="table-empty">Nenhum fornecedor conectado ao MySQL ainda. A estrutura está pronta no schema.</div><?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          else :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              foreach ($rows as $row) :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?><div class="table-row"><strong><?= htmlspecialchars($row['name']) ?></strong><span><?= htmlspecialchars($row['contact_email'] ?: '—') ?><br><?= htmlspecialchars($row['phone'] ?: '—') ?></span><span><?= (int)$row['products'] ?></span><span class="status"><?= htmlspecialchars($row['status']) ?></span></div><?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              endforeach;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          endif; ?></div></div>
<?php require __DIR__ . '/../../app/views/includes/footer.php'; ?>
